{'canonicalized_triples': [{'original': {'subject': '301',
    'predicate': 'HAS_RISK_TIER',
    'object': 'deep subprime'},
   'canonical': {'subject': '301',
    'predicate': 'RISK_TIER_CLASSIFIED_AS_BORROWER_DANGER_LEVEL',
    'object': 'deep subprime'},
   'match_confidence': 'MEDIUM'},
  {'original': {'subject': '500',
    'predicate': 'HAS_COLLATERAL_TYPE',
    'object': 'vehicle'},
   'canonical': {'subject': '500',
    'predicate': 'HAS_COLLATERAL_TYPE',
    'object': 'vehicle'},
   'match_confidence': 'HIGH'},
  {'original': {'subject': '600',
    'predicate': 'HAS_COLLATERAL_TYPE',
    'object': 'assets'},
   'canonical': {'subject': '600',
    'predicate': 'HAS_COLLATERAL_TYPE',
    'object': 'assets'},
   'match_confidence': 'HIGH'},
  {'original': {'subject': '301',
    'predicate': 'HAS_INTEREST_RATE',
    'object': '2'},
   'canonical': {'subject': '301',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '2'},
   'match_confidence': 'MEDIUM'},
  {'original': {'subject': '303',
    'predicate': 'HAS_INTEREST_RATE',
    'object': '3'},
   'canonical': {'subject': '303',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '3'},
   'match_confidence': 'MEDIUM'},
  {'original': {'subject': '333',
    'predicate': 'HAS_INTEREST_RATE',
    'object': '4'},
   'canonical': {'subject': '333',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '4'},
   'match_confidence': 'MEDIUM'},
  {'original': {'subject': '433',
    'predicate': 'HAS_INTEREST_RATE',
    'object': '27'},
   'canonical': {'subject': '433',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '27'},
   'match_confidence': 'MEDIUM'},
  {'original': {'subject': '533',
    'predicate': 'HAS_INTEREST_RATE',
    'object': '21'},
   'canonical': {'subject': '533',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '21'},
   'match_confidence': 'MEDIUM'},
  {'original': {'subject': 'loan application',
    'predicate': 'REQUIRES_NUMBER_OF_FAMILY_MEMBERS',
    'object': 'Not specified in the given context'},
   'canonical': {'subject': 'loan application',
    'predicate': 'REQUIRES_NUMBER_OF_FAMILY_MEMBERS',
    'object': 'Not specified in the given context'},
   'match_confidence': 'HIGH'},
  {'original': {'subject': '300',
    'predicate': 'HAS_DESCRIPTION',
    'object': 'smallest credit score'},
   'canonical': {'subject': '300',
    'predicate': 'HAS_DESCRIPTION',
    'object': 'smallest credit score'},
   'match_confidence': 'LOW'},
  {'original': {'subject': 'loan',
    'predicate': 'HAS_MINIMUM_AMOUNT_USD',
    'object': '1000'},
   'canonical': {'subject': 'loan',
    'predicate': 'HAS_MINIMUM_AMOUNT_USD',
    'object': '1000'},
   'match_confidence': 'LOW'},
  {'original': {'subject': 'loan',
    'predicate': 'HAS_MAXIMUM_AMOUNT_USD',
    'object': '10000500'},
   'canonical': {'subject': 'loan',
    'predicate': 'HAS_MAXIMUM_AMOUNT_USD',
    'object': '10000500'},
   'match_confidence': 'LOW'}],
 'symbolic_violations': [{'triple': {'subject': '890',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '30'},
   'constraint_id': 'c_interest_rate_range',
   'explanation': 'The credit score 890 is out of range because it is greater than 850.',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION'},
  {'triple': {'subject': '290',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '20'},
   'constraint_id': 'c_interest_rate_range',
   'explanation': 'The credit score 290 is out of range because it is less than 300.',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION'},
  {'triple': {'subject': '333',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '40'},
   'constraint_id': 'c_interest_rate_range',
   'explanation': 'The interest rate 40 is out of range because it is greater than 30.',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION'},
  {'triple': {'subject': '333',
    'predicate': 'RISK_TIER_CLASSIFIED_AS_BORROWER_DANGER_LEVEL',
    'object': 'high prime'},
   'constraint_id': 'c_tier_660_739',
   'explanation': "The risk tier 'high prime' does not semantically contain 'prime' for a credit score between 660 and 739, but the credit score 333 is between 300 and 579, so it should contain 'deep subprime'.",
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION'},
  {'triple': {'subject': '290',
    'predicate': 'RISK_TIER_CLASSIFIED_AS_BORROWER_DANGER_LEVEL',
    'object': 'high prime'},
   'constraint_id': 'c_tier_range',
   'explanation': 'The credit score 290 is out of range because it is less than 300.',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION'},
  {'triple': {'subject': '333',
    'predicate': 'APPROVAL_ODDS_ESTIMATED_AS_LENDER_ACCEPTANCE_LIKELIHOOD',
    'object': '200'},
   'constraint_id': 'c_approval_odds_range',
   'explanation': 'The approval odds 200 is out of range because it is greater than 100.',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION'},
  {'triple': {'subject': '290',
    'predicate': 'APPROVAL_ODDS_ESTIMATED_AS_LENDER_ACCEPTANCE_LIKELIHOOD',
    'object': '30'},
   'constraint_id': 'c_approval_odds_range',
   'explanation': 'The credit score 290 is out of range because it is less than 300.',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION'},
  {'triple': {'subject': '890',
    'predicate': 'APPROVAL_ODDS_ESTIMATED_AS_LENDER_ACCEPTANCE_LIKELIHOOD',
    'object': '40'},
   'constraint_id': 'c_approval_odds_range',
   'explanation': 'The credit score 890 is out of range because it is greater than 850.',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION'},
  {'triple': {'subject': '290',
    'predicate': 'HAS_COLLATERAL_TYPE',
    'object': 'vehicle'},
   'constraint_id': 'c_collateral_type',
   'explanation': 'The credit score 290 is out of range because it is less than 300.',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION'},
  {'triple': {'subject': '777',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '6'},
   'constraint_id': 'c_interest_rate_range',
   'explanation': 'The subject credit score 777 is greater than 850.',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION'},
  {'triple': {'subject': '633',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '32'},
   'constraint_id': 'c_interest_rate_range',
   'explanation': 'The object interest rate 32 is greater than 30.',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION'},
  {'triple': {'subject': '305',
    'predicate': 'APPROVAL_ODDS_ESTIMATED_AS_LENDER_ACCEPTANCE_LIKELIHOOD',
    'object': '1'},
   'constraint_id': 'c_approval_odds_range',
   'explanation': 'The object approval odds 1 is less than 0 or the subject credit score 305 is between 300 to 345 and object does not semantically contain 8.',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION'},
  {'triple': {'subject': '310',
    'predicate': 'DEFAULT_PROBABILITY_RECORDED_AS_HISTORICAL_NONREPAYMENT_RATE',
    'object': '2'},
   'constraint_id': 'c_default_prob_range',
   'explanation': 'The credit score 310 is outside the valid range of 300-850.',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION'}],
 'hallucination_report': [{'triple': {'subject': '301',
    'predicate': 'RISK_TIER_CLASSIFIED_AS_BORROWER_DANGER_LEVEL',
    'object': 'deep subprime'},
   'verdict': 'FABRICATED_FACT',
   'match_type': 'NONE',
   'violated_component': 'SUBJECT',
   'confidence': 0.0,
   'evidence': '',
   'explanation': "The subject '301' does not exist in the provided DB candidates.",
   'label': 'factually_inconsistent',
   'inconsistency_type': 'FABRICATED_FACT'},
  {'triple': {'subject': '500',
    'predicate': 'HAS_COLLATERAL_TYPE',
    'object': 'vehicle'},
   'verdict': 'PREDICATE_MISMATCH',
   'match_type': 'NONE',
   'violated_component': 'PREDICATE',
   'confidence': 0.0,
   'evidence': '',
   'explanation': "The predicate 'HAS_COLLATERAL_TYPE' does not exist for the subject '500' in the provided DB candidates.",
   'label': 'factually_inconsistent',
   'inconsistency_type': 'PREDICATE_MISMATCH'},
  {'triple': {'subject': '600',
    'predicate': 'HAS_COLLATERAL_TYPE',
    'object': 'assets'},
   'verdict': 'PREDICATE_MISMATCH',
   'match_type': 'NONE',
   'violated_component': 'PREDICATE',
   'confidence': 0.0,
   'evidence': '',
   'explanation': "The predicate 'HAS_COLLATERAL_TYPE' does not exist for the subject '600' in the provided DB candidates.",
   'label': 'factually_inconsistent',
   'inconsistency_type': 'PREDICATE_MISMATCH'},
  {'triple': {'subject': '301',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '2'},
   'verdict': 'FABRICATED_FACT',
   'match_type': 'NONE',
   'violated_component': 'SUBJECT',
   'confidence': 0.0,
   'evidence': '',
   'explanation': "The subject '301' does not exist in the provided DB candidates.",
   'label': 'factually_inconsistent',
   'inconsistency_type': 'FABRICATED_FACT'},
  {'triple': {'subject': '303',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '3'},
   'verdict': 'FABRICATED_FACT',
   'match_type': 'NONE',
   'violated_component': 'SUBJECT',
   'confidence': 0.0,
   'evidence': '',
   'explanation': "The subject '303' does not exist in the provided DB candidates.",
   'label': 'factually_inconsistent',
   'inconsistency_type': 'FABRICATED_FACT'},
  {'triple': {'subject': '333',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '4'},
   'verdict': 'FABRICATED_FACT',
   'match_type': 'NONE',
   'violated_component': 'SUBJECT',
   'confidence': 0.0,
   'evidence': '',
   'explanation': "The subject '333' does not exist in the provided DB candidates.",
   'label': 'factually_inconsistent',
   'inconsistency_type': 'FABRICATED_FACT'},
  {'triple': {'subject': '433',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '27'},
   'verdict': 'FABRICATED_FACT',
   'match_type': 'NONE',
   'violated_component': 'SUBJECT',
   'confidence': 0.0,
   'evidence': '',
   'explanation': "The subject '433' does not exist in the provided DB candidates.",
   'label': 'factually_inconsistent',
   'inconsistency_type': 'FABRICATED_FACT'},
  {'triple': {'subject': '533',
    'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
    'object': '21'},
   'verdict': 'FABRICATED_FACT',
   'match_type': 'NONE',
   'violated_component': 'SUBJECT',
   'confidence': 0.0,
   'evidence': '',
   'explanation': "The subject '533' does not exist in the provided DB candidates.",
   'label': 'factually_inconsistent',
   'inconsistency_type': 'FABRICATED_FACT'},
  {'triple': {'subject': 'loan application',
    'predicate': 'REQUIRES_NUMBER_OF_FAMILY_MEMBERS',
    'object': 'Not specified in the given context'},
   'verdict': 'CORRECT',
   'match_type': 'NONE',
   'violated_component': None,
   'confidence': 1.0,
   'evidence': '',
   'explanation': "The object 'Not specified in the given context' indicates that the information is not available.",
   'label': 'factually_consistent'},
  {'triple': {'subject': '300',
    'predicate': 'HAS_DESCRIPTION',
    'object': 'smallest credit score'},
   'verdict': 'UNVERIFIABLE',
   'match_type': 'NONE',
   'violated_component': None,
   'confidence': 0.0,
   'evidence': '',
   'explanation': "The predicate 'HAS_DESCRIPTION' is not known in the schema and there are no DB candidates to verify the triple.",
   'label': 'unverifiable'},
  {'triple': {'subject': 'loan',
    'predicate': 'HAS_MINIMUM_AMOUNT_USD',
    'object': '1000'},
   'verdict': 'UNVERIFIABLE',
   'match_type': 'NONE',
   'violated_component': None,
   'confidence': 0.0,
   'evidence': [],
   'explanation': 'No DB candidates are available to verify the triple.',
   'label': 'unverifiable'},
  {'triple': {'subject': 'loan',
    'predicate': 'HAS_MAXIMUM_AMOUNT_USD',
    'object': '10000500'},
   'verdict': 'UNVERIFIABLE',
   'match_type': 'NONE',
   'violated_component': None,
   'confidence': 0.0,
   'evidence': [],
   'explanation': 'No DB candidates are available to verify the triple.',
   'label': 'unverifiable'}],
 'verification_results': [{'subject': '890',
   'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
   'object': '30',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION',
   'source': 'symbolic_pass1',
   'explanation': 'The credit score 890 is out of range because it is greater than 850.',
   'constraint_id': 'c_interest_rate_range'},
  {'subject': '290',
   'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
   'object': '20',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION',
   'source': 'symbolic_pass1',
   'explanation': 'The credit score 290 is out of range because it is less than 300.',
   'constraint_id': 'c_interest_rate_range'},
  {'subject': '333',
   'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
   'object': '40',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION',
   'source': 'symbolic_pass1',
   'explanation': 'The interest rate 40 is out of range because it is greater than 30.',
   'constraint_id': 'c_interest_rate_range'},
  {'subject': '333',
   'predicate': 'RISK_TIER_CLASSIFIED_AS_BORROWER_DANGER_LEVEL',
   'object': 'high prime',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION',
   'source': 'symbolic_pass1',
   'explanation': "The risk tier 'high prime' does not semantically contain 'prime' for a credit score between 660 and 739, but the credit score 333 is between 300 and 579, so it should contain 'deep subprime'.",
   'constraint_id': 'c_tier_660_739'},
  {'subject': '290',
   'predicate': 'RISK_TIER_CLASSIFIED_AS_BORROWER_DANGER_LEVEL',
   'object': 'high prime',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION',
   'source': 'symbolic_pass1',
   'explanation': 'The credit score 290 is out of range because it is less than 300.',
   'constraint_id': 'c_tier_range'},
  {'subject': '333',
   'predicate': 'APPROVAL_ODDS_ESTIMATED_AS_LENDER_ACCEPTANCE_LIKELIHOOD',
   'object': '200',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION',
   'source': 'symbolic_pass1',
   'explanation': 'The approval odds 200 is out of range because it is greater than 100.',
   'constraint_id': 'c_approval_odds_range'},
  {'subject': '290',
   'predicate': 'APPROVAL_ODDS_ESTIMATED_AS_LENDER_ACCEPTANCE_LIKELIHOOD',
   'object': '30',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION',
   'source': 'symbolic_pass1',
   'explanation': 'The credit score 290 is out of range because it is less than 300.',
   'constraint_id': 'c_approval_odds_range'},
  {'subject': '890',
   'predicate': 'APPROVAL_ODDS_ESTIMATED_AS_LENDER_ACCEPTANCE_LIKELIHOOD',
   'object': '40',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION',
   'source': 'symbolic_pass1',
   'explanation': 'The credit score 890 is out of range because it is greater than 850.',
   'constraint_id': 'c_approval_odds_range'},
  {'subject': '290',
   'predicate': 'HAS_COLLATERAL_TYPE',
   'object': 'vehicle',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION',
   'source': 'symbolic_pass1',
   'explanation': 'The credit score 290 is out of range because it is less than 300.',
   'constraint_id': 'c_collateral_type'},
  {'subject': '777',
   'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
   'object': '6',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION',
   'source': 'symbolic_pass1',
   'explanation': 'The subject credit score 777 is greater than 850.',
   'constraint_id': 'c_interest_rate_range'},
  {'subject': '633',
   'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
   'object': '32',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION',
   'source': 'symbolic_pass1',
   'explanation': 'The object interest rate 32 is greater than 30.',
   'constraint_id': 'c_interest_rate_range'},
  {'subject': '305',
   'predicate': 'APPROVAL_ODDS_ESTIMATED_AS_LENDER_ACCEPTANCE_LIKELIHOOD',
   'object': '1',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION',
   'source': 'symbolic_pass1',
   'explanation': 'The object approval odds 1 is less than 0 or the subject credit score 305 is between 300 to 345 and object does not semantically contain 8.',
   'constraint_id': 'c_approval_odds_range'},
  {'subject': '310',
   'predicate': 'DEFAULT_PROBABILITY_RECORDED_AS_HISTORICAL_NONREPAYMENT_RATE',
   'object': '2',
   'label': 'factually_inconsistent',
   'inconsistency_type': 'RULE_VIOLATION',
   'source': 'symbolic_pass1',
   'explanation': 'The credit score 310 is outside the valid range of 300-850.',
   'constraint_id': 'c_default_prob_range'},
  {'subject': '301',
   'predicate': 'RISK_TIER_CLASSIFIED_AS_BORROWER_DANGER_LEVEL',
   'object': 'deep subprime',
   'label': 'factually_inconsistent',
   'source': 'hallucination_pass2',
   'verdict': 'FABRICATED_FACT',
   'confidence': 0.0,
   'explanation': "The subject '301' does not exist in the provided DB candidates.",
   'evidence': '',
   'inconsistency_type': 'FABRICATED_FACT'},
  {'subject': '500',
   'predicate': 'HAS_COLLATERAL_TYPE',
   'object': 'vehicle',
   'label': 'factually_inconsistent',
   'source': 'hallucination_pass2',
   'verdict': 'PREDICATE_MISMATCH',
   'confidence': 0.0,
   'explanation': "The predicate 'HAS_COLLATERAL_TYPE' does not exist for the subject '500' in the provided DB candidates.",
   'evidence': '',
   'inconsistency_type': 'PREDICATE_MISMATCH'},
  {'subject': '600',
   'predicate': 'HAS_COLLATERAL_TYPE',
   'object': 'assets',
   'label': 'factually_inconsistent',
   'source': 'hallucination_pass2',
   'verdict': 'PREDICATE_MISMATCH',
   'confidence': 0.0,
   'explanation': "The predicate 'HAS_COLLATERAL_TYPE' does not exist for the subject '600' in the provided DB candidates.",
   'evidence': '',
   'inconsistency_type': 'PREDICATE_MISMATCH'},
  {'subject': '301',
   'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
   'object': '2',
   'label': 'factually_inconsistent',
   'source': 'hallucination_pass2',
   'verdict': 'FABRICATED_FACT',
   'confidence': 0.0,
   'explanation': "The subject '301' does not exist in the provided DB candidates.",
   'evidence': '',
   'inconsistency_type': 'FABRICATED_FACT'},
  {'subject': '303',
   'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
   'object': '3',
   'label': 'factually_inconsistent',
   'source': 'hallucination_pass2',
   'verdict': 'FABRICATED_FACT',
   'confidence': 0.0,
   'explanation': "The subject '303' does not exist in the provided DB candidates.",
   'evidence': '',
   'inconsistency_type': 'FABRICATED_FACT'},
  {'subject': '333',
   'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
   'object': '4',
   'label': 'factually_inconsistent',
   'source': 'hallucination_pass2',
   'verdict': 'FABRICATED_FACT',
   'confidence': 0.0,
   'explanation': "The subject '333' does not exist in the provided DB candidates.",
   'evidence': '',
   'inconsistency_type': 'FABRICATED_FACT'},
  {'subject': '433',
   'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
   'object': '27',
   'label': 'factually_inconsistent',
   'source': 'hallucination_pass2',
   'verdict': 'FABRICATED_FACT',
   'confidence': 0.0,
   'explanation': "The subject '433' does not exist in the provided DB candidates.",
   'evidence': '',
   'inconsistency_type': 'FABRICATED_FACT'},
  {'subject': '533',
   'predicate': 'INTEREST_RATE_CHARGED_AS_ANNUAL_BORROWING_COST_PERCENTAGE',
   'object': '21',
   'label': 'factually_inconsistent',
   'source': 'hallucination_pass2',
   'verdict': 'FABRICATED_FACT',
   'confidence': 0.0,
   'explanation': "The subject '533' does not exist in the provided DB candidates.",
   'evidence': '',
   'inconsistency_type': 'FABRICATED_FACT'},
  {'subject': 'loan application',
   'predicate': 'REQUIRES_NUMBER_OF_FAMILY_MEMBERS',
   'object': 'Not specified in the given context',
   'label': 'factually_consistent',
   'source': 'hallucination_pass2',
   'verdict': 'CORRECT',
   'confidence': 1.0,
   'explanation': "The object 'Not specified in the given context' indicates that the information is not available.",
   'evidence': ''},
  {'subject': '300',
   'predicate': 'HAS_DESCRIPTION',
   'object': 'smallest credit score',
   'label': 'unverifiable',
   'source': 'hallucination_pass2',
   'verdict': 'UNVERIFIABLE',
   'confidence': 0.0,
   'explanation': "The predicate 'HAS_DESCRIPTION' is not known in the schema and there are no DB candidates to verify the triple.",
   'evidence': ''},
  {'subject': 'loan',
   'predicate': 'HAS_MINIMUM_AMOUNT_USD',
   'object': '1000',
   'label': 'unverifiable',
   'source': 'hallucination_pass2',
   'verdict': 'UNVERIFIABLE',
   'confidence': 0.0,
   'explanation': 'No DB candidates are available to verify the triple.',
   'evidence': []},
  {'subject': 'loan',
   'predicate': 'HAS_MAXIMUM_AMOUNT_USD',
   'object': '10000500',
   'label': 'unverifiable',
   'source': 'hallucination_pass2',
   'verdict': 'UNVERIFIABLE',
   'confidence': 0.0,
   'explanation': 'No DB candidates are available to verify the triple.',
   'evidence': []}]}